Jon-Becker/heimdall-rs

common/src/ether/signatures.rs
heimdall/src/decompile/mod.rs

This PR reduces the number of collisions when decompiling contracts that contain events. 
The `Transfer(address,address,uint256)` event on USDC implementation contract (`0xa2327a938febf5fec13bacfb16ae10ecbc4cbdcf`) currently results in a collision. 
The current resolution request is:
https://sig.eth.samczsun.com/api/v1/signatures?all=true&function=0xddf252ad
With this update, we use the full 32 byte hash and the event api, to reduce the likelihood of collisions.
https://sig.eth.samczsun.com/api/v1/signatures?all=true&event=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef

fix(decompile): use 32 byte hash for events to reduce collisions

---

common/src/ether/evm/tests.rs
common/src/ether/evm/vm.rs

- Reduce number of unnecessary operations within `_step`.
- Addresses potential overflow on `I256::shr` while waiting for official patch.
- Minor fixes
- Adds a few tests for more thorough VM opcode testing

:zap: perf: vm performance improvements & fixes

---

common/src/constants.rs
common/src/ether/evm/vm.rs
heimdall/src/decompile/analyze.rs
heimdall/src/decompile/util.rs

Memory and storage accesses will also be taken into account when checking if the stack diff of a `JUMPI` modifies a given JUMPI condition, indicating a loop.

:wrench: fix: loop detection to take into account memory and storage

---

common/src/ether/signatures.rs

When fetching the signature from `openchain.xyz`, by default the results are filter.
For example https://api.openchain.xyz/signature-database/v1/lookup?filter=false&function=0x06fdde03 returns:
```
{"ok":true,"result":{"event":{},"function":{"0x06fdde03":[{"name":"name()","filtered":false},{"name":"message_hour(uint256,int8,uint16,bytes32)","filtered":true}]}}}
```
https://api.openchain.xyz/signature-database/v1/lookup?function=0x06fdde03 returns:
```
{"ok":true,"result":{"event":{},"function":{"0x06fdde03":[{"name":"name()","filtered":false}]}}}
```

:wrench: fix: Get all the results from openchain

---

heimdall/src/decompile/output.rs

It would be useful to output the full signature hash of events when the resolution is skipped. Currently, it only writes the first 8 bytes, but event signatures are not "compressed" like function ones; they are always used as a whole.
For example, instead of having:
```
Event_ddf252ad
```
it should output:
```
Event_ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
```
Having the full signature is useful, it can be used to retrieve logs or perform reverse hashing afterward.
I also fixed the use of the struct, it was using the ErrorABI struct instead of the EventABI one.

Output full event signatures on unresolved ABI

---

common/src/ether/signatures.rs
heimdall/src/decode/mod.rs
heimdall/src/decompile/mod.rs

I noticed that, in case of multiple reverse hashes found, it always proposes the last option available. 
This is often not the most used signature, in most cases it's the first one. It would be better to select the first one as default.
I modified the code to put as default the one with index 0.
For example:

fix: default signature resolution

---

common/src/ether/evm/ext/disassemble.rs
heimdall/src/cfg/mod.rs
heimdall/src/decompile/mod.rs
heimdall/src/snapshot/mod.rs

SSIA. Support the bytecode file which has a new line at the end of the file. (e.g., vim / cat saved files)

:wrench: fix: replace newline characters on the bytecode

---

core/src/snapshot/util/table.rs

This PR fixes Issue #178 
- I first create a vector sorted_snapshots from the relevant slice of snapshots.
- Then, I sort sorted_snapshots in place using sort_by.
- Finally, I iterate over sorted_snapshots to build the rows.
I could have implement `Ord` trait for `Snapshot` , but it seemed an overkill to me, as this is the only place in the codebase so far that requires such ordering. Once new sorting cases appears, the trait approach must be more suitable.
_Demo_

feat(snapshot): sort selectors ascending

---

cli/src/main.rs

Fixes #181
Simply fetches chain id from rpc and includes on the path of snapshot file.

feat: separate outputs by chain

---

core/src/snapshot/analyze.rs

Resolves #190 
It's not enough to only filter where a cast is all `f` nibbles, we need to also check for `0` nibbles as well (for bitwise masking reasons).
If a `PUSH`ed string contains only `f`s or `0`s, we don't assume it's an address.

fix(snapshot): add partial bitwise masking case exclusion

---

cli/src/main.rs
cli/src/output.rs
core/src/cfg/mod.rs
core/src/cfg/output.rs
core/src/decompile/mod.rs
core/src/disassemble/mod.rs
core/src/dump/mod.rs
core/src/snapshot/mod.rs
core/src/snapshot/util/csv.rs
core/tests/test_cfg.rs
core/tests/test_decompile.rs
core/tests/test_disassemble.rs
core/tests/test_snapshot.rs

resolves https://github.com/Jon-Becker/heimdall-rs/issues/179

feat(cli): add `--output` flag

---

cli/src/main.rs
cli/src/output.rs
less

Long outputs (such as `heimdall disassemble 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 -d --output print`) get truncated because of their line count.
Use `less` to display these outputs.

perf(cli): use `less` for `--output print` handling

---

Cargo.lock
common/Cargo.toml
common/src/ether/rpc.rs

`heimdall_common::ether::rpc` functions don't implement any sort of retrying, leading to [issues](https://github.com/Jon-Becker/heimdall-rs/issues/192) when calls bump up against rate-limits.
Closes #194 
Implement exponential backoff retrying for these RPC functions.

feat(rpc): add exponential backoff to rpc methods

---

common/src/ether/evm/core/vm.rs

fix(evm): SHL/SHR `shift > 255` check must come before operation

---

core/src/decode/mod.rs
core/src/inspect/core/tracing.rs
core/tests/test_inspect.rs

fix(inspect): fix panics within `wei_to_ether`, `decode`

---

core/src/cfg/mod.rs
core/src/decode/mod.rs
core/src/decompile/mod.rs
core/src/disassemble/mod.rs
core/src/dump/mod.rs
core/src/heimdall.rs
core/src/inspect/mod.rs

chore: `heimdall-common` replacements

---

common/src/ether/evm/ext/exec/jump_frame.rs
common/src/ether/evm/ext/exec/mod.rs
common/src/ether/evm/ext/exec/util.rs
common/src/utils/range_map.rs
core/tests/test_decompile.rs

Adds symbolic execution heuristic `jump_stack_depth_less_than_max_stack_depth` which ensures we only handle growing stacks. I.e, if the current `stack_depth` for the `JumpFrame` is 30, but we have `max_stack_depth` of 72, we don't need to cover this as it will likely grow forever (and cause hanging).
Fixes #167

fix(symbolic-execution): add growth loop-detection heuristic

---

common/src/ether/evm/ext/exec/mod.rs
common/src/ether/evm/ext/exec/util.rs
core/tests/test_decompile.rs

This PR will allow symbolic execution to break out of infinite `JUMP` loops (not just `JUMPI`).
Closes #253

fix(symbolic-exec): break out of infinite `JUMP` loops

---

common/src/ether/evm/ext/exec/mod.rs
common/src/ether/evm/ext/exec/util.rs
common/src/utils/threading.rs
core/src/cfg/mod.rs
core/src/decompile/mod.rs
core/src/snapshot/mod.rs
core/tests/test_cfg.rs
core/tests/test_decompile.rs
core/tests/test_snapshot.rs

Closes #254, motivated by #253

feat(symbolic-execution): implement & utilize `run_with_timeout`

---

common/src/ether/evm/ext/exec/util.rs
common/src/utils/range_map.rs
core/src/decompile/mod.rs
core/src/decompile/out/postprocessers/solidity.rs
core/src/decompile/out/postprocessers/yul.rs
core/src/snapshot/analyze.rs
core/src/snapshot/mod.rs
core/src/snapshot/resolve.rs

chore(clippy): make clippy happy

---

Cargo.lock
cache/Cargo.toml
cache/src/error.rs
cache/src/lib.rs
common/Cargo.toml
common/src/error.rs
common/src/ether/bytecode.rs
common/src/ether/rpc.rs
common/src/ether/selectors.rs
common/src/ether/signatures.rs
common/src/lib.rs
core/src/decode/mod.rs
core/src/inspect/core/logs.rs

chore: remove panicky `unwrap()`s, use `Result<(), ..>

---

common/src/utils/range_map.rs

I failed to run `heavy_test_snapshot_thorough` test in the file `core/tests/test_snapshot.rs` 
I always encoutered a substract underflow error. 
After investigation, I believe there is something wrong within the original `write` function in the file `common/src/utils/range_map.rs`. There is something wrong when merging new `range` and `incumbents`
I rewrote part of the code. 
It's the same logic but in a straightforward implementation. It has shorter lines of code and easier to maintain. 
After my fix, now `heavy_test_snapshot_thorough` can pass without any error.

fix(vm): range underflow error

---

common/src/ether/evm/core/types.rs
core/src/decode/core/abi.rs
core/src/decode/mod.rs
core/tests/test_decode.rs

fix(decode): various decode fixes introduced in f168506

---

common/src/ether/lexers/cleanup.rs

fix(tests): update test cases for postprocessing cleanup

---

common/src/ether/selectors.rs
common/src/resources/transpose.rs
common/src/utils/io/logging.rs
common/src/utils/io/macros.rs
common/src/utils/range_map.rs
core/src/cfg/mod.rs
core/src/decode/mod.rs
core/src/decompile/analyzers/yul.rs
core/src/decompile/mod.rs
core/src/decompile/out/abi.rs
core/src/decompile/out/solidity.rs
core/src/decompile/out/yul.rs
core/src/dump/util/threads/indexer.rs
core/src/snapshot/mod.rs
core/src/snapshot/resolve.rs

chore(logger): abstract logging methods to macros

---

core/src/decompile/analyzers/solidity.rs
core/src/decompile/analyzers/yul.rs
core/src/decompile/mod.rs
core/src/decompile/out/abi.rs
core/src/decompile/out/postprocessers/solidity.rs
core/src/decompile/out/postprocessers/yul.rs
core/src/decompile/out/solidity.rs
core/src/decompile/out/yul.rs
core/src/decompile/util.rs
core/tests/test_decompile.rs

If resolving selectors fails due to an unsupported compiler, we can still decompile the contract's bytecode as if it were the fallback function.
Ex:

feat(decompile): support all contracts regardless of compiler

---

cli/src/main.rs
core/src/cfg/mod.rs
core/src/decode/mod.rs
core/src/decompile/mod.rs
core/src/disassemble/mod.rs
core/src/dump/mod.rs
core/src/inspect/core/tracing.rs
core/src/inspect/mod.rs
core/src/snapshot/mod.rs

fix(decode): dont output trace if `--quiet` is set

---

crates/cli/Cargo.toml
crates/common/src/ether/signatures.rs
crates/core/Cargo.toml
crates/core/tests/test_decompile.rs
crates/decompile/Cargo.toml
crates/decompile/src/core/out/abi.rs
crates/decompile/src/utils/heuristics/arguments.rs

Heimdall-rs uses now alloy-json-abi to handle the ABI in decompile step, but the library doesn't accept the "bytes memory" as a token for an output type.
- Change "bytes memory" to "bytes" in the ABI output string. 
- The steps to serialize and deserialize are added to the `heavy_test_decompile_thorough` UT. 
- Upgraded alloy-json-abi to 0.7.4.

fix: change "bytes memory" to "bytes" in json abi output

---

Cargo.lock
crates/cfg/Cargo.toml
crates/cli/Cargo.toml
crates/common/Cargo.toml
crates/common/src/ether/mod.rs
crates/common/src/ether/signatures.rs
crates/common/src/ether/types.rs
crates/core/Cargo.toml
crates/decode/Cargo.toml
crates/decode/src/core/mod.rs
crates/decompile/Cargo.toml
crates/decompile/src/core/out/abi.rs
crates/decompile/src/core/out/source.rs
crates/decompile/src/core/resolve.rs
crates/dump/Cargo.toml
crates/inspect/Cargo.toml
crates/vm/Cargo.toml
crates/vm/src/core/memory.rs
crates/vm/src/core/vm.rs
crates/vm/src/ext/mod.rs
crates/vm/src/ext/range_map.rs

Closes #439 
yes
also marks unused vm memory range_map as `--features experimental`, prevents some vm overflows

fix(decompile): handle tuple arguments correctly in ABI/source generation

---

examples/python/README.md
examples/python/main.py

chore(examples): add python example

---

README.md

chore: update `README.md`

---

README.md

Heimdall was used in research submitted to ISSTA 2024. This change reflects that in the proper section of the README.
The academic citations section of README is out of date.
Update it?..

chore(readme): update academic citations section

---

crates/cli/src/main.rs
crates/decompile/src/utils/heuristics/arguments.rs

feat(decompile): default `openai_api_key` to configured value if empty

---

crates/decompile/src/core/out/source.rs

perf(decompile): harden llm postprocessing, will not hard error

---

crates/vm/src/core/vm.rs

fix(vm): `JUMPI` dest overflow check

---

.gitignore
Cargo.lock
crates/cli/src/main.rs
crates/common/src/ether/signatures.rs
crates/core/tests/test_decode.rs
crates/decode/Cargo.toml
crates/decode/src/interfaces/args.rs
examples/typescript/README.md
examples/typescript/index.ts
examples/typescript/package.json

feat(decode): `-o`/`--output` support

---

crates/vm/src/core/vm.rs

Fixes "safe" conversion from `Uint<256>` to `usize`. 
The solution is to saturate at `usize::MAX` if there is an overflow rather than panic.
I've implemented this for opcodes where the `offset.saturating_add(size)` is clamped to a specific value so as not to affect execution.
Closes #545

fix(vm): fix "safe" conversions from `Uint<256>` to `usize`

---

crates/core/tests/test_decompile.rs
crates/vm/src/core/vm.rs

feat: fix `Uint<256>` conversion issues by clamping values

---

Cargo.lock
crates/cfg/Cargo.toml
crates/cfg/src/core/graph.rs
crates/cfg/src/core/mod.rs
crates/common/src/ether/types.rs
crates/core/tests/test_cfg.rs
crates/vm/src/core/types.rs
crates/vm/src/core/vm.rs

Fix this issue: https://github.com/Jon-Becker/heimdall-rs/issues/499
Subtract 1 from the index, which is `operation.last_instruction.instruction`, thereby shifting the overall offset to start from 0x00 (currently starting from 0x01).
I believe this approach is appropriate. Because the downstream program does not seem to use this offset, and this offset only serves as the destination for opcodes such as `JumpI` and related opcodes.
> Attention: The full testing has not been completed, so it is unclear whether it will affect other content. (I am not familiar with this repository). Therefore, please identify and test thoroughly.

fix(cfg): graph starts from offset `0x01` instead of `0x00`, prune redundant nodes

---

crates/common/src/ether/bytecode.rs
crates/common/src/ether/rpc.rs
crates/core/tests/test_disassemble.rs

cc @chen4903 
we treat 20-byte strings as an address, but if fetching bytecode fails we can return the bytes and assume they are disassembling/decompiling some exactly 20 byte contract
the reason i had to remove the code in your PR was just that the .unwrap() on the decode_hex() call could fail, and was making one of the tests unhappy. i believe this approach is more robust as well

fix(bytecode): handle edge case where bytcode is exactly 20 bytes

---

README.md

Heimdall-RS has been cited in more academic writing than the original README suggests; this pull request rectifies that oversight.
I have also decided to follow the American Psychological Association’s latest style guide with a best-effort approach.

feat: update citations

---

Cargo.lock
crates/cfg/Cargo.toml
crates/cli/Cargo.toml
crates/common/Cargo.toml
crates/common/src/ether/calldata.rs
crates/common/src/ether/provider.rs
crates/common/src/ether/rpc.rs
crates/core/Cargo.toml
crates/decode/Cargo.toml
crates/decode/src/core/mod.rs
crates/decode/src/utils/abi.rs
crates/decompile/Cargo.toml
crates/dump/Cargo.toml
crates/inspect/Cargo.toml
crates/inspect/src/core/mod.rs
crates/vm/Cargo.toml

With recent release of alloy 1.0 it's a good opportunity to align to it.
Not many changes, mainly simplifying the MultiTransportProvider provider wrapper, which I think is still a good abstraction that can come in handy.

chore(deps): upgrade `alloy` to `1.0`
