Jon-Becker/heimdall-rs

heimdall/src/decompile/mod.rs
heimdall/src/decompile/output.rs
heimdall/src/decompile/util.rs

- Limit branches to 1000 unique branches
- Will eventually be a parameter
- Implement natspec comments for deubgging
- Argument natspec include potential types, in order of confidence.

🔀 merge: v2.0.1 changes

---

README.md

Script from https://doc.rust-lang.org/cargo/getting-started/installation.html

Add Rust/Cargo dependency to install instructions

---

common/src/ether/signatures.rs

:sparkles: feat: switch to etherface over openchain

---

heimdall/src/decode/mod.rs

Just caught this typo today. Yeah, I know... I promise to contribute in a more valuable way in the future 😅

✏️ typo: in the "missing rpc" message

---

Cargo.lock
Cargo.toml
cache/Cargo.toml
cache/src/lib.rs
common/Cargo.toml
common/src/ether/evm/disassemble.rs
common/src/ether/selectors.rs
common/src/utils/http.rs
common/src/utils/mod.rs
common/src/utils/version.rs
config/Cargo.toml
config/src/lib.rs
heimdall/Cargo.toml
heimdall/src/decode/mod.rs
heimdall/src/decompile/mod.rs
heimdall/src/decompile/out/postprocessers/solidity.rs
heimdall/src/heimdall.rs
rustfmt.toml

- Core heimdall vm can encounter execution locks during `VM::_step()`

🔧 fix: heimdall core vm execution lock

---

common/src/ether/evm/disassemble.rs
common/src/io/logging.rs
heimdall/src/cfg/mod.rs
heimdall/src/decode/mod.rs
heimdall/src/decompile/mod.rs
heimdall/src/dump/mod.rs
heimdall/src/dump/util/mod.rs
heimdall/src/dump/util/threads/indexer.rs

:zap: perf: quiet support for all modules

---

common/src/ether/evm/ext/disassemble.rs
heimdall/src/cfg/mod.rs
heimdall/src/decompile/mod.rs
heimdall/src/dump/util/table.rs
heimdall/src/snapshot/mod.rs
heimdall/tests/test_disassemble.rs

:star2: qol: default disassembly to hex, with decimal options

---

Cargo.lock
Cargo.toml
cache/Cargo.toml
cache/src/tests.rs
common/Cargo.toml
common/src/ether/evm/core/tests.rs
common/src/ether/evm/core/types.rs
common/src/ether/lexers/solidity.rs
common/src/ether/signatures.rs
common/src/utils/http.rs
common/src/utils/version.rs
config/Cargo.toml
heimdall/Cargo.toml
heimdall/src/decompile/analyzers/solidity.rs
heimdall/src/decompile/analyzers/yul.rs
heimdall/src/snapshot/analyze.rs
heimdall/src/snapshot/menus/command_palette.rs
heimdall/src/snapshot/menus/main.rs
scripts/clippy

Will close #140 
Will also drastically improve decode performance

⚡ perf: Improve decode module performance & accuracy

---

cache/src/util.rs
common/src/ether/compiler.rs
common/src/ether/evm/core/opcodes.rs
common/src/ether/evm/core/stack.rs
common/src/ether/evm/core/types.rs
common/src/ether/evm/ext/disassemble.rs
common/src/ether/evm/ext/exec/mod.rs
common/src/ether/evm/ext/exec/util.rs
common/src/ether/rpc.rs
common/src/ether/selectors.rs
common/src/ether/signatures.rs
common/src/io/logging.rs
common/src/io/tests.rs
common/src/resources/openai.rs
common/src/resources/transpose.rs
common/src/utils/strings.rs
heimdall/src/cfg/mod.rs
heimdall/src/cfg/output.rs
heimdall/src/decode/mod.rs
heimdall/src/decode/util.rs
heimdall/src/decompile/mod.rs
heimdall/src/decompile/out/solidity.rs
heimdall/src/decompile/out/yul.rs
heimdall/src/dump/mod.rs
heimdall/src/heimdall.rs
heimdall/src/snapshot/mod.rs
heimdall/tests/test_cfg.rs
heimdall/tests/test_decode.rs

🔧  fix: symbolic execution loop detection

---

Cargo.lock
Cargo.toml
cache/Cargo.toml
cli/Cargo.toml
common/Cargo.toml
common/src/ether/rpc.rs
config/Cargo.toml
core/Cargo.toml
core/src/dump/util/mod.rs
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decompile/Cargo.toml
examples/dump/Cargo.toml
examples/snapshot/Cargo.toml

⚡ perf: make cache chain-specific & qol changes

---

.github/workflows/todo.yml

fix(ci): add issue template to todo.yml workflow

---

common/src/ether/signatures.rs
common/src/utils/io/logging.rs
core/src/decompile/resolve.rs
core/src/snapshot/resolve.rs

chore: deprecate etherface, switch to openchain

---

core/tests/test_decode.rs

fix(tests): set decode success threshold to 0.93

---

cache/src/lib.rs
cache/src/util.rs
cli/src/output.rs
common/src/ether/compiler.rs
common/src/ether/evm/core/types.rs
common/src/ether/evm/ext/exec/mod.rs
common/src/ether/evm/ext/exec/util.rs
common/src/ether/rpc.rs
common/src/ether/selectors.rs
common/src/ether/signatures.rs
common/src/utils/http.rs
common/src/utils/io/logging.rs
common/src/utils/io/macros.rs
common/src/utils/strings.rs
core/src/cfg/mod.rs
core/src/decompile/analyzers/yul.rs
core/src/decompile/mod.rs
core/src/decompile/out/abi.rs
core/src/decompile/out/postprocessers/solidity.rs
core/src/decompile/out/postprocessers/yul.rs
core/src/decompile/resolve.rs
core/src/dump/util/mod.rs
core/src/dump/util/threads/indexer.rs
core/src/dump/util/threads/tui.rs
core/src/snapshot/analyze.rs
core/src/snapshot/mod.rs
core/src/snapshot/resolve.rs
core/src/snapshot/util/tui.rs

Also would like to eventually abstract *all* logger instances to macros.

chore(logging): use macro `debug_max!(..)` throughout codebase

---

Cargo.lock
common/src/resources/transpose.rs

feat(resources): add exponential backoff to `call_transpose`

---

Cargo.lock
Cargo.toml
cache/Cargo.toml
cli/Cargo.toml
common/Cargo.toml
config/Cargo.toml
core/Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml
examples/snapshot/Cargo.toml

chore(build): bump version to 0.7.0

---

Cargo.lock
Cargo.toml
cache/Cargo.toml
cli/Cargo.toml
common/Cargo.toml
config/Cargo.toml
core/Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml
examples/snapshot/Cargo.toml

chore(build): bump version to 0.7.1

---

.github/workflows/heavy-integration.yml

chore(ci): add `--nocapture` flag to heavy integration tests

---

core/src/decode/core/abi.rs
core/src/decode/mod.rs

chore(decode): cleanup decode, simplify logic, add comments

---

Cargo.lock
Cargo.toml
cache/Cargo.toml
cli/Cargo.toml
common/Cargo.toml
config/Cargo.toml
core/Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml
examples/snapshot/Cargo.toml

chore(build): bump version to 0.7.2

---

bifrost/bifrost
common/src/utils/version.rs

feat(bifrost): add *hacky* nightly build system

---

common/src/ether/rpc.rs
common/src/ether/signatures.rs

fix(rpc): fix RPC backoff, add tests

---

Cargo.lock
Cargo.toml
cache/Cargo.toml
cli/Cargo.toml
common/Cargo.toml
config/Cargo.toml
core/Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml
examples/snapshot/Cargo.toml

chore(build): bump version to 0.7.3

---

core/src/decode/mod.rs

fix(decode): if skip-resolving returns an `Err`, use fallback

---

Cargo.lock
cache/src/lib.rs
cache/src/util.rs
cli/Cargo.toml
cli/src/error.rs
cli/src/main.rs
cli/src/output.rs
common/src/utils/threading.rs
scripts/test

chore(cli): remove panicky `unwrap()`s, use Result<(), ..>`

---

common/src/constants.rs

fix(bytecode): `BYTECODE_REGEX` needs *

---

cache/src/lib.rs
cache/src/util.rs
cli/src/main.rs
common/src/ether/bytecode.rs
common/src/ether/compiler.rs
common/src/ether/evm/core/types.rs
common/src/ether/lexers/cleanup.rs
common/src/ether/rpc.rs
common/src/utils/iter.rs
common/src/utils/strings.rs
core/src/cfg/mod.rs
core/src/decode/core/abi.rs
core/src/decode/mod.rs
core/src/decode/util.rs
core/src/decompile/mod.rs
core/src/decompile/out/postprocessers/solidity.rs
core/src/decompile/out/postprocessers/yul.rs
core/src/disassemble/mod.rs
core/src/snapshot/mod.rs
core/src/snapshot/util/tui.rs
scripts/byte.py

[DRAFT] chore: convert all instances of bytecode, calldata to Vec<u8>

---

core/src/decompile/out/postprocessers/solidity.rs

fix(decompile): solidity postprocessing things

---

.config/nextest.toml

feat(tests): add nextest.toml for backoff

---

examples/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decode_offline/all_selectors.csv
examples/decode_offline/canonical.yaml
examples/decode_offline/src/main.rs

This is a simple example to decode raw bytecode without using internet
i wanted to avoid useless spam towards openchainxyz API and decrease the time needed for the decode
loaded an hashMap with all the selectors from openchainxyz  and checked against the results.
(adding .skip_resolving(true) to decode() call)

decode offline example with local selectors

---

common/src/ether/evm/core/vm.rs

fix(vm): clamp `CALLDATACOPY` offset & size to prevent vec overflow

---

core/tests/test_decode.rs
core/tests/test_inspect.rs

test(inspect): dont count `RpcError` as failure case

---

common/src/resources/openai.rs
core/src/decode/util.rs

fix(common): update openai model to `gpt-3.5-turbo-instruct`

---

bifrost/bifrost

feat(bifrost): `try`/`catch` based build system update

---

crates/core/src/snapshot/mod.rs

fix(snapshot): fail-fast if no selectors were found

---

bifrost/README.md
crates/common/src/ether/compiler.rs
crates/common/src/ether/lexers/cleanup.rs
crates/common/src/resources/transpose.rs
crates/common/src/utils/testing/benchmarks.rs
crates/core/src/decompile/out/postprocessers/solidity.rs
crates/core/src/snapshot/structures/snapshot.rs

1. Fix `bifrost/README.md` typo
2. Fix `crates/common/src/ether/compiler.rs` typo
3. Fix `crates/common/src/ether/lexers/cleanup.rs` typo
4. Fix `crates/common/src/resources/transpose.rs` typo
5. Fix `crates/common/src/utils/testing/benchmarks.rs` typo
6. Fix `crates/core/src/decompile/out/postprocessers/solidity.rs` typo
7. Fix `crates/core/src/snapshot/structures/snapshot.rs` typo

chore: fix typos

---

crates/common/src/error.rs
crates/common/src/ether/evm/core/vm.rs
crates/common/src/ether/evm/ext/exec/mod.rs

feat(vm): orphan branches which cause panics during symbolic execution

---

crates/core/tests/test_decompile.rs
crates/decompile/src/core/postprocess.rs
crates/decompile/src/utils/heuristics/arguments.rs
crates/decompile/src/utils/postprocessors/memory.rs

feat(decompile): increased accuracy wrt return types, variable type inference

---

crates/common/src/constants.rs
crates/common/src/ether/evm/ext/exec/mod.rs
crates/core/tests/test_decode.rs
crates/decode/src/core/mod.rs
crates/decode/src/interfaces/args.rs
crates/decode/src/utils/constructor.rs
crates/decode/src/utils/mod.rs

closes #389 
on nightly,
```
heimdall decode 60806040526006805460ff191690556020600781905560085560006009819055600a8181556027600b55602d600c556014600d55600e9190915562000047906012906200037b565b6200005690621e848062000393565b600f55620000676012600a6200037b565b6200007690621e848062000393565b601055620000876012600a6200037b565b62000095906101f462000393565b601155620000a66012600a6200037b565b620000b5906207a12062000393565b6012556014805461ffff60a81b19169055348015620000d357600080fd5b5060405162001de938038062001de9833981016040819052620000f691620003ad565b600080546001600160a01b031916339081178255604051909182917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0908290a35060068054610100600160a81b0319166101006001600160a01b03841602179055620001656012600a6200037b565b62000175906305f5e10062000393565b3360009 …
```

feat(decode): parse & decode constructor arguments from deployment bytecode

---

crates/decompile/src/utils/postprocessors/variable.rs

fix(decompile): only replace entire exprs with known variables

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml
examples/snapshot/Cargo.toml

meta: bump version to `0.8.0`

---

crates/common/src/ether/signatures.rs
crates/decode/src/core/mod.rs
crates/decompile/src/core/mod.rs

perf(decode): improve `score_signature` heuristic

---

crates/decompile/src/core/resolve.rs

fix(decompile): skip invalid signatures where `sig.params.len() < analyzed_function.params.len()`

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml
examples/snapshot/Cargo.toml

meta: bump version to `0.8.1`

---

crates/common/src/ether/bytecode.rs
crates/common/src/ether/compiler.rs
crates/common/src/ether/rpc.rs
crates/core/tests/test_inspect.rs

feat(compiler): more accurate compiler detection via heuristics

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml
examples/snapshot/Cargo.toml

chore(meta): bump version to `0.8.2`

---

.github/workflows/tests.yml
crates/cli/src/output.rs
crates/common/src/ether/bytecode.rs
crates/common/src/ether/calldata.rs
crates/common/src/ether/http_or_ws_or_ipc.rs
crates/common/src/ether/rpc.rs
crates/core/tests/test_cfg.rs
crates/core/tests/test_decode.rs
crates/core/tests/test_decompile.rs
crates/core/tests/test_disassemble.rs

chore(tests): tests to use `RPC_URL`, `WS_RPC_URL` from env

---

crates/cfg/src/core/graph.rs

fix(cfg): `lazy_static` persists across calls (bad), and is not needed

---

.config/nextest.toml
.github/workflows/heavy-integration.yml
.gitignore
crates/cfg/src/core/graph.rs
crates/core/tests/test_cfg.rs
crates/core/tests/test_decode.rs
crates/core/tests/test_decompile.rs
crates/core/tests/test_disassemble.rs
crates/core/tests/test_inspect.rs

chore(tests): heavy integration to use large dataset

---

.github/INTEGRATION_FAILURE.md
.github/workflows/heavy-integration.yml

fix(tests): heavy integration tests runs w/ env

---

.github/workflows/heavy-integration.yml
Cargo.lock
Cargo.toml
crates/cfg/src/core/mod.rs
crates/common/src/utils/threading.rs
crates/core/Cargo.toml
crates/core/tests/test_cfg.rs
crates/core/tests/test_decompile.rs
crates/core/tests/test_disassemble.rs
crates/decompile/src/core/mod.rs
crates/vm/src/core/memory.rs
crates/vm/src/core/stack.rs
crates/vm/src/core/vm.rs
crates/vm/src/ext/exec/mod.rs

fix(tests): heavy integration test debugging

---

Cargo.toml
crates/cfg/src/core/mod.rs
crates/core/tests/test_decode.rs
crates/core/tests/test_inspect.rs
crates/decode/src/lib.rs
crates/decompile/src/core/mod.rs
crates/dump/src/lib.rs
crates/inspect/src/lib.rs

perf: remove redundant clones, cleanup

---

FUNDING.json

meta(funding): add `FUNDING.json`

---

crates/vm/src/core/vm.rs

fix(vm): clamp memory offsets/sizes to sane values

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml

chore(meta): bump version to `0.8.3`

---

crates/decompile/src/core/out/abi.rs

fix(decompile): filter fallback from ABI generation

---

crates/cli/src/main.rs
crates/common/src/utils/version.rs

feat(cli): auto-check for new nightly version if on nightly

---

Cargo.lock
crates/cfg/src/core/mod.rs
crates/cfg/src/interfaces/args.rs
crates/cli/Cargo.toml
crates/cli/src/args.rs
crates/cli/src/main.rs
crates/common/src/ether/bytecode.rs
crates/common/src/ether/calldata.rs
crates/decode/src/core/mod.rs
crates/decode/src/interfaces/args.rs
crates/decompile/src/core/mod.rs
crates/decompile/src/interfaces/args.rs
crates/disassemble/src/core/mod.rs
crates/disassemble/src/interfaces/args.rs

chore: add `get_bytecode`, `get_calldata` to args

---

crates/common/src/ether/provider.rs
crates/common/src/ether/signatures.rs

Noticed one leftover store_cache, deemed unnecessary by new with_cache.
Removed.

fix(common): redundant store_cache removed

---

Cargo.lock
crates/common/src/ether/types.rs
crates/decode/Cargo.toml
crates/inspect/Cargo.toml
crates/inspect/src/interfaces/traces.rs

feat(inspect): hack to serialize `DynSolValue` for `decodedInputs` / `decodedOutputs`

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml

chore(meta): bump version to 0.8.4

---

crates/dump/src/core/mod.rs
crates/dump/src/interfaces/args.rs

fix(dump): rpc sanity check for `trace_replayBlockTransactions`

---

README.md

chore(readme): update academic citations

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml

chore(meta): bump version to 0.8.5

---

examples/typescript/index.ts

feat(examples): fix typescript example

---

Cargo.lock

This reverts commit 838bc5a9142f8549cea2840f554cd1ad8eeba3ab.

Revert "chore(deps): weekly `cargo update` (#535)"

---

README.md

docs: Update academic paper citations in README.md

---

crates/core/tests/test_decompile.rs
crates/vm/src/core/vm.rs

fix(vm): `CODECOPY`, `CALLDATACOPY`, `MCOPY` size clamping

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml

chore: bump version to `0.8.7`

---

rust-toolchain.toml

chore(deps): bump rust version to `1.82.0`

---

crates/inspect/src/interfaces/traces.rs

fix(inspect): call value displaying as `0 wei`

---

Cargo.lock
Cargo.toml

chore(deps): add `ansi` feature to `tracing-subscriber`

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/cfg/Cargo.toml
examples/decode/Cargo.toml
examples/decode_offline/Cargo.toml
examples/decompile/Cargo.toml
examples/disassemble/Cargo.toml
examples/dump/Cargo.toml
examples/inspect/Cargo.toml

chore: bump version to `0.9.0`

---

crates/decode/src/core/mod.rs

fix(decode): remove hardcoded multicall signatures

---

.github/workflows/heavy-integration.yml

chore: reduce heavy integration run count
